name: GitHub Actions Calculator

on:
  push:
    branches: ['calc']

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: install jest
        run: npm install --g jest
        working-directory: calc
      - name: run the test
        run: npm run test ----coverage
        working-directory: calc